### PR TITLE
SMS-1 - Added h1 styles

### PR DESCRIPTION
**Pull request by becma**
added styles to h1

### CODE REVIEW

**Comment by jams1810** [comment]
apprové

**Comment by Eveelyne** [comment]
Test

**Review by ghost — APPROVED** [review]
Thumbs Up!

**Review by PatriciaTee — APPROVED** [review]

**Review by jams1810 — APPROVED** [review]
Apprové encore!!

**Review by jpgjessica — APPROVED** [review]

**Review by ClemeDigs — APPROVED** [review]

**Review by Eveelyne — APPROVED** [review]

**Review by ririroy — APPROVED** [review]

**Review by Mbouchard93 — APPROVED** [review]

**Review by alicia-ross — APPROVED** [review]

**Pull request merged**
